/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest3;

/**
 *
 * @author Spitzery
 */
public class Layout extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    public Layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelUtama = new javax.swing.JPanel();
        tengah = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pprof = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pinfo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pbout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        asal = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        nooo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        login1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        login = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        simpan2 = new javax.swing.JButton();
        atas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bawah = new javax.swing.JPanel();
        kanan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        pro = new javax.swing.JButton();
        Information = new javax.swing.JButton();
        abt = new javax.swing.JButton();
        kiri = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelUtama.setLayout(new java.awt.BorderLayout(2, 2));

        tengah.setBackground(new java.awt.Color(255, 255, 255));
        tengah.setLayout(new java.awt.CardLayout());

        phome.setBackground(new java.awt.Color(102, 102, 102));
        phome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest3/tutoring.jpg"))); // NOI18N
        phome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 310, 310));

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel5.setText("sELAMAT DATANG");
        phome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        tengah.add(phome, "card2");

        pprof.setBackground(new java.awt.Color(102, 102, 102));
        pprof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest3/bimbingan-belajar-9-638 (1).jpg"))); // NOI18N
        pprof.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        tengah.add(pprof, "card3");

        pinfo.setBackground(new java.awt.Color(102, 102, 102));
        pinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest3/o.jpg"))); // NOI18N
        pinfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tengah.add(pinfo, "card4");

        pbout.setBackground(new java.awt.Color(102, 102, 102));
        pbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Nama");
        pbout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        pbout.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 182, -1));

        jLabel9.setText("Jenis Kelamin");
        pbout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Laki - Laki");
        pbout.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        pbout.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel10.setText("Daerah Asal");
        pbout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        asal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Samarinda", "Penajam Paser Utara", "Sangatta", "Bontang", "Itci", "Balikpapan" }));
        pbout.add(asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel11.setText("ALAMAT");
        pbout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        pbout.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 239, -1));

        jLabel12.setText("NO. TELP");
        pbout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        a.setText("+62");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        pbout.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 56, -1));

        nooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noooActionPerformed(evt);
            }
        });
        pbout.add(nooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 132, -1));

        jLabel13.setText("--");
        pbout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 16, -1));

        simpan.setText("SIMPAN");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        pbout.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel14.setText("Register");
        pbout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 38, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("SUDAH PUNYA AKUN ? SILAHKAN LOGIN DISINI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pbout.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jPanel4.setLayout(new java.awt.CardLayout());

        login1.setBackground(new java.awt.Color(102, 102, 102));

        area.setBackground(new java.awt.Color(102, 102, 102));
        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout login1Layout = new javax.swing.GroupLayout(login1);
        login1.setLayout(login1Layout);
        login1Layout.setHorizontalGroup(
            login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        login1Layout.setVerticalGroup(
            login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.add(login1, "card2");

        login.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setText("Username");

        jLabel16.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        simpan2.setText("Login");
        simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(53, 53, 53)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(jTextField2))
                .addGap(199, 199, 199))
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(simpan2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addComponent(simpan2)
                .addGap(37, 37, 37))
        );

        jPanel4.add(login, "card3");

        pbout.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 560, 230));

        tengah.add(pbout, "card5");

        panelUtama.add(tengah, java.awt.BorderLayout.CENTER);

        atas.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Zery Dery");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Posttest3/1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIMBINGAN BELAJAR");

        javax.swing.GroupLayout atasLayout = new javax.swing.GroupLayout(atas);
        atas.setLayout(atasLayout);
        atasLayout.setHorizontalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(atasLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(359, Short.MAX_VALUE))))
        );
        atasLayout.setVerticalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUtama.add(atas, java.awt.BorderLayout.PAGE_START);

        bawah.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout bawahLayout = new javax.swing.GroupLayout(bawah);
        bawah.setLayout(bawahLayout);
        bawahLayout.setHorizontalGroup(
            bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        bawahLayout.setVerticalGroup(
            bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelUtama.add(bawah, java.awt.BorderLayout.PAGE_END);

        kanan.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        home.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home);

        pro.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pro.setText("Profile");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jPanel2.add(pro);

        Information.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Information.setText("Information");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });
        jPanel2.add(Information);

        abt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        abt.setText("Register/Login");
        abt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });
        jPanel2.add(abt);

        javax.swing.GroupLayout kananLayout = new javax.swing.GroupLayout(kanan);
        kanan.setLayout(kananLayout);
        kananLayout.setHorizontalGroup(
            kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kananLayout.setVerticalGroup(
            kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        panelUtama.add(kanan, java.awt.BorderLayout.LINE_END);

        kiri.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kiriLayout = new javax.swing.GroupLayout(kiri);
        kiri.setLayout(kiriLayout);
        kiriLayout.setHorizontalGroup(
            kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        kiriLayout.setVerticalGroup(
            kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );

        panelUtama.add(kiri, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void noooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noooActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked

    }//GEN-LAST:event_simpanMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        phome.setVisible(true);
        pbout.setVisible(false);
        pinfo.setVisible(false);
        pprof.setVisible(false);
        login.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
        phome.setVisible(false);
        pbout.setVisible(false);
        pinfo.setVisible(false);
        pprof.setVisible(true);
        login.setVisible(false);
    }//GEN-LAST:event_proActionPerformed

    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed
        // TODO add your handling code here:
        phome.setVisible(false);
        pbout.setVisible(false);
        pinfo.setVisible(true);
        pprof.setVisible(false);
        login.setVisible(false);
    }//GEN-LAST:event_InformationActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
        // TODO add your handling code here:
        phome.setVisible(false);
        pbout.setVisible(true);
        pinfo.setVisible(false);
        pprof.setVisible(false);
        login.setVisible(false);
        login1.setVisible(true);
        //simpan.setEnabled(false);
        //simpan2.setEnabled(false);
    }//GEN-LAST:event_abtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        login.setVisible(true);
        login1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan2ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String nama = nm.getText();
        String kelamin="";
        if (jRadioButton1.isSelected()==true){
            kelamin = "Laki - laki";
        }
        else if (jRadioButton2.isSelected()==true){
            kelamin = "Perempuan";
        }
        else{
            kelamin= "tidak diketahui";
        }
        String asald = asal.getSelectedItem().toString();
        String alt = alamat.getText();
        String no = a.getText();
        String n01 = nooo.getText();
        login1.setVisible(true);
        login.setVisible(false);
        area.setText("Nama \t\t: "+nama+"\nJenis Kelamin \t\t: "+kelamin+"\nDaerah Asal \t\t: "+asald+
                "\nAlamat \t\t: "+alt+"\nNomer \t\t: "+no+" "+n01);
    }//GEN-LAST:event_simpanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        simpan2.setEnabled(false);
        a.setEditable(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Information;
    private javax.swing.JTextField a;
    private javax.swing.JButton abt;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox asal;
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JPanel login;
    private javax.swing.JPanel login1;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField nooo;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel pbout;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel pinfo;
    private javax.swing.JPanel pprof;
    private javax.swing.JButton pro;
    private javax.swing.JButton simpan;
    private javax.swing.JButton simpan2;
    private javax.swing.JPanel tengah;
    // End of variables declaration//GEN-END:variables
}
